#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proiect
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Avioane")]
	public partial class AvioaneDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCompozitie_Rute(Compozitie_Rute instance);
    partial void UpdateCompozitie_Rute(Compozitie_Rute instance);
    partial void DeleteCompozitie_Rute(Compozitie_Rute instance);
    partial void InsertDestinatii(Destinatii instance);
    partial void UpdateDestinatii(Destinatii instance);
    partial void DeleteDestinatii(Destinatii instance);
    partial void InsertRute(Rute instance);
    partial void UpdateRute(Rute instance);
    partial void DeleteRute(Rute instance);
    partial void InsertAvioane(Avioane instance);
    partial void UpdateAvioane(Avioane instance);
    partial void DeleteAvioane(Avioane instance);
    partial void InsertCalatori(Calatori instance);
    partial void UpdateCalatori(Calatori instance);
    partial void DeleteCalatori(Calatori instance);
    partial void InsertBilete(Bilete instance);
    partial void UpdateBilete(Bilete instance);
    partial void DeleteBilete(Bilete instance);
    #endregion
		
		public AvioaneDataContext() : 
				base(global::Proiect.Properties.Settings.Default.AvioaneConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public AvioaneDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AvioaneDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AvioaneDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AvioaneDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Compozitie_Rute> Compozitie_Rutes
		{
			get
			{
				return this.GetTable<Compozitie_Rute>();
			}
		}
		
		public System.Data.Linq.Table<Destinatii> Destinatiis
		{
			get
			{
				return this.GetTable<Destinatii>();
			}
		}
		
		public System.Data.Linq.Table<Rute> Rutes
		{
			get
			{
				return this.GetTable<Rute>();
			}
		}
		
		public System.Data.Linq.Table<Avioane> Avioanes
		{
			get
			{
				return this.GetTable<Avioane>();
			}
		}
		
		public System.Data.Linq.Table<Calatori> Calatoris
		{
			get
			{
				return this.GetTable<Calatori>();
			}
		}
		
		public System.Data.Linq.Table<Data_Curenta> Data_Curentas
		{
			get
			{
				return this.GetTable<Data_Curenta>();
			}
		}
		
		public System.Data.Linq.Table<Bilete> Biletes
		{
			get
			{
				return this.GetTable<Bilete>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Compozitie_Rute")]
	public partial class Compozitie_Rute : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Ruta;
		
		private int _ID_Destinatie;
		
		private EntityRef<Destinatii> _Destinatii;
		
		private EntityRef<Rute> _Rute;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_RutaChanging(int value);
    partial void OnID_RutaChanged();
    partial void OnID_DestinatieChanging(int value);
    partial void OnID_DestinatieChanged();
    #endregion
		
		public Compozitie_Rute()
		{
			this._Destinatii = default(EntityRef<Destinatii>);
			this._Rute = default(EntityRef<Rute>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Ruta", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID_Ruta
		{
			get
			{
				return this._ID_Ruta;
			}
			set
			{
				if ((this._ID_Ruta != value))
				{
					if (this._Rute.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_RutaChanging(value);
					this.SendPropertyChanging();
					this._ID_Ruta = value;
					this.SendPropertyChanged("ID_Ruta");
					this.OnID_RutaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Destinatie", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID_Destinatie
		{
			get
			{
				return this._ID_Destinatie;
			}
			set
			{
				if ((this._ID_Destinatie != value))
				{
					if (this._Destinatii.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_DestinatieChanging(value);
					this.SendPropertyChanging();
					this._ID_Destinatie = value;
					this.SendPropertyChanged("ID_Destinatie");
					this.OnID_DestinatieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Destinatii_Compozitie_Rute", Storage="_Destinatii", ThisKey="ID_Destinatie", OtherKey="ID_Destinatie", IsForeignKey=true)]
		public Destinatii Destinatii
		{
			get
			{
				return this._Destinatii.Entity;
			}
			set
			{
				Destinatii previousValue = this._Destinatii.Entity;
				if (((previousValue != value) 
							|| (this._Destinatii.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Destinatii.Entity = null;
						previousValue.Compozitie_Rutes.Remove(this);
					}
					this._Destinatii.Entity = value;
					if ((value != null))
					{
						value.Compozitie_Rutes.Add(this);
						this._ID_Destinatie = value.ID_Destinatie;
					}
					else
					{
						this._ID_Destinatie = default(int);
					}
					this.SendPropertyChanged("Destinatii");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Rute_Compozitie_Rute", Storage="_Rute", ThisKey="ID_Ruta", OtherKey="ID_Ruta", IsForeignKey=true)]
		public Rute Rute
		{
			get
			{
				return this._Rute.Entity;
			}
			set
			{
				Rute previousValue = this._Rute.Entity;
				if (((previousValue != value) 
							|| (this._Rute.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Rute.Entity = null;
						previousValue.Compozitie_Rutes.Remove(this);
					}
					this._Rute.Entity = value;
					if ((value != null))
					{
						value.Compozitie_Rutes.Add(this);
						this._ID_Ruta = value.ID_Ruta;
					}
					else
					{
						this._ID_Ruta = default(int);
					}
					this.SendPropertyChanged("Rute");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Destinatii")]
	public partial class Destinatii : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Destinatie;
		
		private string _Nume;
		
		private System.Nullable<int> _Pozitie_x;
		
		private System.Nullable<int> _Pozitie_y;
		
		private EntitySet<Compozitie_Rute> _Compozitie_Rutes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_DestinatieChanging(int value);
    partial void OnID_DestinatieChanged();
    partial void OnNumeChanging(string value);
    partial void OnNumeChanged();
    partial void OnPozitie_xChanging(System.Nullable<int> value);
    partial void OnPozitie_xChanged();
    partial void OnPozitie_yChanging(System.Nullable<int> value);
    partial void OnPozitie_yChanged();
    #endregion
		
		public Destinatii()
		{
			this._Compozitie_Rutes = new EntitySet<Compozitie_Rute>(new Action<Compozitie_Rute>(this.attach_Compozitie_Rutes), new Action<Compozitie_Rute>(this.detach_Compozitie_Rutes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Destinatie", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Destinatie
		{
			get
			{
				return this._ID_Destinatie;
			}
			set
			{
				if ((this._ID_Destinatie != value))
				{
					this.OnID_DestinatieChanging(value);
					this.SendPropertyChanging();
					this._ID_Destinatie = value;
					this.SendPropertyChanged("ID_Destinatie");
					this.OnID_DestinatieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nume", DbType="VarChar(MAX)")]
		public string Nume
		{
			get
			{
				return this._Nume;
			}
			set
			{
				if ((this._Nume != value))
				{
					this.OnNumeChanging(value);
					this.SendPropertyChanging();
					this._Nume = value;
					this.SendPropertyChanged("Nume");
					this.OnNumeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pozitie_x", DbType="Int")]
		public System.Nullable<int> Pozitie_x
		{
			get
			{
				return this._Pozitie_x;
			}
			set
			{
				if ((this._Pozitie_x != value))
				{
					this.OnPozitie_xChanging(value);
					this.SendPropertyChanging();
					this._Pozitie_x = value;
					this.SendPropertyChanged("Pozitie_x");
					this.OnPozitie_xChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pozitie_y", DbType="Int")]
		public System.Nullable<int> Pozitie_y
		{
			get
			{
				return this._Pozitie_y;
			}
			set
			{
				if ((this._Pozitie_y != value))
				{
					this.OnPozitie_yChanging(value);
					this.SendPropertyChanging();
					this._Pozitie_y = value;
					this.SendPropertyChanged("Pozitie_y");
					this.OnPozitie_yChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Destinatii_Compozitie_Rute", Storage="_Compozitie_Rutes", ThisKey="ID_Destinatie", OtherKey="ID_Destinatie")]
		public EntitySet<Compozitie_Rute> Compozitie_Rutes
		{
			get
			{
				return this._Compozitie_Rutes;
			}
			set
			{
				this._Compozitie_Rutes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Compozitie_Rutes(Compozitie_Rute entity)
		{
			this.SendPropertyChanging();
			entity.Destinatii = this;
		}
		
		private void detach_Compozitie_Rutes(Compozitie_Rute entity)
		{
			this.SendPropertyChanging();
			entity.Destinatii = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Rute")]
	public partial class Rute : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Ruta;
		
		private string _Inceput;
		
		private string _Final;
		
		private EntitySet<Compozitie_Rute> _Compozitie_Rutes;
		
		private EntitySet<Avioane> _Avioanes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_RutaChanging(int value);
    partial void OnID_RutaChanged();
    partial void OnInceputChanging(string value);
    partial void OnInceputChanged();
    partial void OnFinalChanging(string value);
    partial void OnFinalChanged();
    #endregion
		
		public Rute()
		{
			this._Compozitie_Rutes = new EntitySet<Compozitie_Rute>(new Action<Compozitie_Rute>(this.attach_Compozitie_Rutes), new Action<Compozitie_Rute>(this.detach_Compozitie_Rutes));
			this._Avioanes = new EntitySet<Avioane>(new Action<Avioane>(this.attach_Avioanes), new Action<Avioane>(this.detach_Avioanes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Ruta", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Ruta
		{
			get
			{
				return this._ID_Ruta;
			}
			set
			{
				if ((this._ID_Ruta != value))
				{
					this.OnID_RutaChanging(value);
					this.SendPropertyChanging();
					this._ID_Ruta = value;
					this.SendPropertyChanged("ID_Ruta");
					this.OnID_RutaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Inceput", DbType="VarChar(MAX)")]
		public string Inceput
		{
			get
			{
				return this._Inceput;
			}
			set
			{
				if ((this._Inceput != value))
				{
					this.OnInceputChanging(value);
					this.SendPropertyChanging();
					this._Inceput = value;
					this.SendPropertyChanged("Inceput");
					this.OnInceputChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Final", DbType="VarChar(MAX)")]
		public string Final
		{
			get
			{
				return this._Final;
			}
			set
			{
				if ((this._Final != value))
				{
					this.OnFinalChanging(value);
					this.SendPropertyChanging();
					this._Final = value;
					this.SendPropertyChanged("Final");
					this.OnFinalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Rute_Compozitie_Rute", Storage="_Compozitie_Rutes", ThisKey="ID_Ruta", OtherKey="ID_Ruta")]
		public EntitySet<Compozitie_Rute> Compozitie_Rutes
		{
			get
			{
				return this._Compozitie_Rutes;
			}
			set
			{
				this._Compozitie_Rutes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Rute_Avioane", Storage="_Avioanes", ThisKey="ID_Ruta", OtherKey="ID_Ruta")]
		public EntitySet<Avioane> Avioanes
		{
			get
			{
				return this._Avioanes;
			}
			set
			{
				this._Avioanes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Compozitie_Rutes(Compozitie_Rute entity)
		{
			this.SendPropertyChanging();
			entity.Rute = this;
		}
		
		private void detach_Compozitie_Rutes(Compozitie_Rute entity)
		{
			this.SendPropertyChanging();
			entity.Rute = null;
		}
		
		private void attach_Avioanes(Avioane entity)
		{
			this.SendPropertyChanging();
			entity.Rute = this;
		}
		
		private void detach_Avioanes(Avioane entity)
		{
			this.SendPropertyChanging();
			entity.Rute = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Avioane")]
	public partial class Avioane : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Avion;
		
		private string _Nume;
		
		private System.Nullable<int> _Capacitate;
		
		private System.Nullable<System.TimeSpan> _Ora_inceput;
		
		private System.Nullable<int> _Viteza_medie;
		
		private int _ID_Ruta;
		
		private System.Nullable<System.DateTime> _Data_Reciclare;
		
		private EntitySet<Bilete> _Biletes;
		
		private EntityRef<Rute> _Rute;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_AvionChanging(int value);
    partial void OnID_AvionChanged();
    partial void OnNumeChanging(string value);
    partial void OnNumeChanged();
    partial void OnCapacitateChanging(System.Nullable<int> value);
    partial void OnCapacitateChanged();
    partial void OnOra_inceputChanging(System.Nullable<System.TimeSpan> value);
    partial void OnOra_inceputChanged();
    partial void OnViteza_medieChanging(System.Nullable<int> value);
    partial void OnViteza_medieChanged();
    partial void OnID_RutaChanging(int value);
    partial void OnID_RutaChanged();
    partial void OnData_ReciclareChanging(System.Nullable<System.DateTime> value);
    partial void OnData_ReciclareChanged();
    #endregion
		
		public Avioane()
		{
			this._Biletes = new EntitySet<Bilete>(new Action<Bilete>(this.attach_Biletes), new Action<Bilete>(this.detach_Biletes));
			this._Rute = default(EntityRef<Rute>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Avion", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Avion
		{
			get
			{
				return this._ID_Avion;
			}
			set
			{
				if ((this._ID_Avion != value))
				{
					this.OnID_AvionChanging(value);
					this.SendPropertyChanging();
					this._ID_Avion = value;
					this.SendPropertyChanged("ID_Avion");
					this.OnID_AvionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nume", DbType="NVarChar(MAX)")]
		public string Nume
		{
			get
			{
				return this._Nume;
			}
			set
			{
				if ((this._Nume != value))
				{
					this.OnNumeChanging(value);
					this.SendPropertyChanging();
					this._Nume = value;
					this.SendPropertyChanged("Nume");
					this.OnNumeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Capacitate", DbType="Int")]
		public System.Nullable<int> Capacitate
		{
			get
			{
				return this._Capacitate;
			}
			set
			{
				if ((this._Capacitate != value))
				{
					this.OnCapacitateChanging(value);
					this.SendPropertyChanging();
					this._Capacitate = value;
					this.SendPropertyChanged("Capacitate");
					this.OnCapacitateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ora_inceput", DbType="Time")]
		public System.Nullable<System.TimeSpan> Ora_inceput
		{
			get
			{
				return this._Ora_inceput;
			}
			set
			{
				if ((this._Ora_inceput != value))
				{
					this.OnOra_inceputChanging(value);
					this.SendPropertyChanging();
					this._Ora_inceput = value;
					this.SendPropertyChanged("Ora_inceput");
					this.OnOra_inceputChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Viteza_medie", DbType="Int")]
		public System.Nullable<int> Viteza_medie
		{
			get
			{
				return this._Viteza_medie;
			}
			set
			{
				if ((this._Viteza_medie != value))
				{
					this.OnViteza_medieChanging(value);
					this.SendPropertyChanging();
					this._Viteza_medie = value;
					this.SendPropertyChanged("Viteza_medie");
					this.OnViteza_medieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Ruta", DbType="Int NOT NULL")]
		public int ID_Ruta
		{
			get
			{
				return this._ID_Ruta;
			}
			set
			{
				if ((this._ID_Ruta != value))
				{
					if (this._Rute.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_RutaChanging(value);
					this.SendPropertyChanging();
					this._ID_Ruta = value;
					this.SendPropertyChanged("ID_Ruta");
					this.OnID_RutaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Data_Reciclare", DbType="Date")]
		public System.Nullable<System.DateTime> Data_Reciclare
		{
			get
			{
				return this._Data_Reciclare;
			}
			set
			{
				if ((this._Data_Reciclare != value))
				{
					this.OnData_ReciclareChanging(value);
					this.SendPropertyChanging();
					this._Data_Reciclare = value;
					this.SendPropertyChanged("Data_Reciclare");
					this.OnData_ReciclareChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Avioane_Bilete", Storage="_Biletes", ThisKey="ID_Avion", OtherKey="ID_Avion")]
		public EntitySet<Bilete> Biletes
		{
			get
			{
				return this._Biletes;
			}
			set
			{
				this._Biletes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Rute_Avioane", Storage="_Rute", ThisKey="ID_Ruta", OtherKey="ID_Ruta", IsForeignKey=true)]
		public Rute Rute
		{
			get
			{
				return this._Rute.Entity;
			}
			set
			{
				Rute previousValue = this._Rute.Entity;
				if (((previousValue != value) 
							|| (this._Rute.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Rute.Entity = null;
						previousValue.Avioanes.Remove(this);
					}
					this._Rute.Entity = value;
					if ((value != null))
					{
						value.Avioanes.Add(this);
						this._ID_Ruta = value.ID_Ruta;
					}
					else
					{
						this._ID_Ruta = default(int);
					}
					this.SendPropertyChanged("Rute");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Biletes(Bilete entity)
		{
			this.SendPropertyChanging();
			entity.Avioane = this;
		}
		
		private void detach_Biletes(Bilete entity)
		{
			this.SendPropertyChanging();
			entity.Avioane = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Calatori")]
	public partial class Calatori : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Calator;
		
		private string _Loc;
		
		private string _Nume;
		
		private string _Prenume;
		
		private string _Adresa;
		
		private string _Telefon;
		
		private string _Detalii_Buletin;
		
		private string _CNP;
		
		private EntitySet<Bilete> _Biletes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_CalatorChanging(int value);
    partial void OnID_CalatorChanged();
    partial void OnLocChanging(string value);
    partial void OnLocChanged();
    partial void OnNumeChanging(string value);
    partial void OnNumeChanged();
    partial void OnPrenumeChanging(string value);
    partial void OnPrenumeChanged();
    partial void OnAdresaChanging(string value);
    partial void OnAdresaChanged();
    partial void OnTelefonChanging(string value);
    partial void OnTelefonChanged();
    partial void OnDetalii_BuletinChanging(string value);
    partial void OnDetalii_BuletinChanged();
    partial void OnCNPChanging(string value);
    partial void OnCNPChanged();
    #endregion
		
		public Calatori()
		{
			this._Biletes = new EntitySet<Bilete>(new Action<Bilete>(this.attach_Biletes), new Action<Bilete>(this.detach_Biletes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Calator", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Calator
		{
			get
			{
				return this._ID_Calator;
			}
			set
			{
				if ((this._ID_Calator != value))
				{
					this.OnID_CalatorChanging(value);
					this.SendPropertyChanging();
					this._ID_Calator = value;
					this.SendPropertyChanged("ID_Calator");
					this.OnID_CalatorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Loc", DbType="VarChar(MAX)")]
		public string Loc
		{
			get
			{
				return this._Loc;
			}
			set
			{
				if ((this._Loc != value))
				{
					this.OnLocChanging(value);
					this.SendPropertyChanging();
					this._Loc = value;
					this.SendPropertyChanged("Loc");
					this.OnLocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nume", DbType="VarChar(MAX)")]
		public string Nume
		{
			get
			{
				return this._Nume;
			}
			set
			{
				if ((this._Nume != value))
				{
					this.OnNumeChanging(value);
					this.SendPropertyChanging();
					this._Nume = value;
					this.SendPropertyChanged("Nume");
					this.OnNumeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prenume", DbType="VarChar(MAX)")]
		public string Prenume
		{
			get
			{
				return this._Prenume;
			}
			set
			{
				if ((this._Prenume != value))
				{
					this.OnPrenumeChanging(value);
					this.SendPropertyChanging();
					this._Prenume = value;
					this.SendPropertyChanged("Prenume");
					this.OnPrenumeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adresa", DbType="VarChar(MAX)")]
		public string Adresa
		{
			get
			{
				return this._Adresa;
			}
			set
			{
				if ((this._Adresa != value))
				{
					this.OnAdresaChanging(value);
					this.SendPropertyChanging();
					this._Adresa = value;
					this.SendPropertyChanged("Adresa");
					this.OnAdresaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefon", DbType="VarChar(MAX)")]
		public string Telefon
		{
			get
			{
				return this._Telefon;
			}
			set
			{
				if ((this._Telefon != value))
				{
					this.OnTelefonChanging(value);
					this.SendPropertyChanging();
					this._Telefon = value;
					this.SendPropertyChanged("Telefon");
					this.OnTelefonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Detalii_Buletin", DbType="VarChar(MAX)")]
		public string Detalii_Buletin
		{
			get
			{
				return this._Detalii_Buletin;
			}
			set
			{
				if ((this._Detalii_Buletin != value))
				{
					this.OnDetalii_BuletinChanging(value);
					this.SendPropertyChanging();
					this._Detalii_Buletin = value;
					this.SendPropertyChanged("Detalii_Buletin");
					this.OnDetalii_BuletinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CNP", DbType="VarChar(MAX)")]
		public string CNP
		{
			get
			{
				return this._CNP;
			}
			set
			{
				if ((this._CNP != value))
				{
					this.OnCNPChanging(value);
					this.SendPropertyChanging();
					this._CNP = value;
					this.SendPropertyChanged("CNP");
					this.OnCNPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Calatori_Bilete", Storage="_Biletes", ThisKey="ID_Calator", OtherKey="ID_Calator")]
		public EntitySet<Bilete> Biletes
		{
			get
			{
				return this._Biletes;
			}
			set
			{
				this._Biletes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Biletes(Bilete entity)
		{
			this.SendPropertyChanging();
			entity.Calatori = this;
		}
		
		private void detach_Biletes(Bilete entity)
		{
			this.SendPropertyChanging();
			entity.Calatori = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Data_Curenta")]
	public partial class Data_Curenta
	{
		
		private System.Nullable<System.DateTime> _Data_Curenta1;
		
		private System.Nullable<int> _Data_singulara;
		
		public Data_Curenta()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Data_Curenta", Storage="_Data_Curenta1", DbType="Date")]
		public System.Nullable<System.DateTime> Data_Curenta1
		{
			get
			{
				return this._Data_Curenta1;
			}
			set
			{
				if ((this._Data_Curenta1 != value))
				{
					this._Data_Curenta1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Data_singulara", DbType="Int")]
		public System.Nullable<int> Data_singulara
		{
			get
			{
				return this._Data_singulara;
			}
			set
			{
				if ((this._Data_singulara != value))
				{
					this._Data_singulara = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Bilete")]
	public partial class Bilete : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Bilet;
		
		private int _ID_Avion;
		
		private System.Nullable<System.DateTime> _Data;
		
		private System.Nullable<int> _Cod;
		
		private string _Destinatie_1;
		
		private string _Destinatie_2;
		
		private System.Nullable<System.TimeSpan> _Ora_Decolare;
		
		private System.Nullable<System.TimeSpan> _Ora_Aterizare;
		
		private System.Nullable<int> _ID_Calator;
		
		private System.Nullable<int> _Checkin;
		
		private string _Optiuni;
		
		private System.Nullable<int> _Loc;
		
		private System.Nullable<int> _Pret;
		
		private EntityRef<Avioane> _Avioane;
		
		private EntityRef<Calatori> _Calatori;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_BiletChanging(int value);
    partial void OnID_BiletChanged();
    partial void OnID_AvionChanging(int value);
    partial void OnID_AvionChanged();
    partial void OnDataChanging(System.Nullable<System.DateTime> value);
    partial void OnDataChanged();
    partial void OnCodChanging(System.Nullable<int> value);
    partial void OnCodChanged();
    partial void OnDestinatie_1Changing(string value);
    partial void OnDestinatie_1Changed();
    partial void OnDestinatie_2Changing(string value);
    partial void OnDestinatie_2Changed();
    partial void OnOra_DecolareChanging(System.Nullable<System.TimeSpan> value);
    partial void OnOra_DecolareChanged();
    partial void OnOra_AterizareChanging(System.Nullable<System.TimeSpan> value);
    partial void OnOra_AterizareChanged();
    partial void OnID_CalatorChanging(System.Nullable<int> value);
    partial void OnID_CalatorChanged();
    partial void OnCheckinChanging(System.Nullable<int> value);
    partial void OnCheckinChanged();
    partial void OnOptiuniChanging(string value);
    partial void OnOptiuniChanged();
    partial void OnLocChanging(System.Nullable<int> value);
    partial void OnLocChanged();
    partial void OnPretChanging(System.Nullable<int> value);
    partial void OnPretChanged();
    #endregion
		
		public Bilete()
		{
			this._Avioane = default(EntityRef<Avioane>);
			this._Calatori = default(EntityRef<Calatori>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Bilet", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Bilet
		{
			get
			{
				return this._ID_Bilet;
			}
			set
			{
				if ((this._ID_Bilet != value))
				{
					this.OnID_BiletChanging(value);
					this.SendPropertyChanging();
					this._ID_Bilet = value;
					this.SendPropertyChanged("ID_Bilet");
					this.OnID_BiletChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Avion", DbType="Int NOT NULL")]
		public int ID_Avion
		{
			get
			{
				return this._ID_Avion;
			}
			set
			{
				if ((this._ID_Avion != value))
				{
					if (this._Avioane.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_AvionChanging(value);
					this.SendPropertyChanging();
					this._ID_Avion = value;
					this.SendPropertyChanged("ID_Avion");
					this.OnID_AvionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Data", DbType="Date")]
		public System.Nullable<System.DateTime> Data
		{
			get
			{
				return this._Data;
			}
			set
			{
				if ((this._Data != value))
				{
					this.OnDataChanging(value);
					this.SendPropertyChanging();
					this._Data = value;
					this.SendPropertyChanged("Data");
					this.OnDataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cod", DbType="Int")]
		public System.Nullable<int> Cod
		{
			get
			{
				return this._Cod;
			}
			set
			{
				if ((this._Cod != value))
				{
					this.OnCodChanging(value);
					this.SendPropertyChanging();
					this._Cod = value;
					this.SendPropertyChanged("Cod");
					this.OnCodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Destinatie_1", DbType="VarChar(MAX)")]
		public string Destinatie_1
		{
			get
			{
				return this._Destinatie_1;
			}
			set
			{
				if ((this._Destinatie_1 != value))
				{
					this.OnDestinatie_1Changing(value);
					this.SendPropertyChanging();
					this._Destinatie_1 = value;
					this.SendPropertyChanged("Destinatie_1");
					this.OnDestinatie_1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Destinatie_2", DbType="VarChar(MAX)")]
		public string Destinatie_2
		{
			get
			{
				return this._Destinatie_2;
			}
			set
			{
				if ((this._Destinatie_2 != value))
				{
					this.OnDestinatie_2Changing(value);
					this.SendPropertyChanging();
					this._Destinatie_2 = value;
					this.SendPropertyChanged("Destinatie_2");
					this.OnDestinatie_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ora_Decolare", DbType="Time")]
		public System.Nullable<System.TimeSpan> Ora_Decolare
		{
			get
			{
				return this._Ora_Decolare;
			}
			set
			{
				if ((this._Ora_Decolare != value))
				{
					this.OnOra_DecolareChanging(value);
					this.SendPropertyChanging();
					this._Ora_Decolare = value;
					this.SendPropertyChanged("Ora_Decolare");
					this.OnOra_DecolareChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ora_Aterizare", DbType="Time")]
		public System.Nullable<System.TimeSpan> Ora_Aterizare
		{
			get
			{
				return this._Ora_Aterizare;
			}
			set
			{
				if ((this._Ora_Aterizare != value))
				{
					this.OnOra_AterizareChanging(value);
					this.SendPropertyChanging();
					this._Ora_Aterizare = value;
					this.SendPropertyChanged("Ora_Aterizare");
					this.OnOra_AterizareChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Calator", DbType="Int")]
		public System.Nullable<int> ID_Calator
		{
			get
			{
				return this._ID_Calator;
			}
			set
			{
				if ((this._ID_Calator != value))
				{
					if (this._Calatori.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_CalatorChanging(value);
					this.SendPropertyChanging();
					this._ID_Calator = value;
					this.SendPropertyChanged("ID_Calator");
					this.OnID_CalatorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Checkin", DbType="Int")]
		public System.Nullable<int> Checkin
		{
			get
			{
				return this._Checkin;
			}
			set
			{
				if ((this._Checkin != value))
				{
					this.OnCheckinChanging(value);
					this.SendPropertyChanging();
					this._Checkin = value;
					this.SendPropertyChanged("Checkin");
					this.OnCheckinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Optiuni", DbType="VarChar(MAX)")]
		public string Optiuni
		{
			get
			{
				return this._Optiuni;
			}
			set
			{
				if ((this._Optiuni != value))
				{
					this.OnOptiuniChanging(value);
					this.SendPropertyChanging();
					this._Optiuni = value;
					this.SendPropertyChanged("Optiuni");
					this.OnOptiuniChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Loc", DbType="Int")]
		public System.Nullable<int> Loc
		{
			get
			{
				return this._Loc;
			}
			set
			{
				if ((this._Loc != value))
				{
					this.OnLocChanging(value);
					this.SendPropertyChanging();
					this._Loc = value;
					this.SendPropertyChanged("Loc");
					this.OnLocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pret", DbType="Int")]
		public System.Nullable<int> Pret
		{
			get
			{
				return this._Pret;
			}
			set
			{
				if ((this._Pret != value))
				{
					this.OnPretChanging(value);
					this.SendPropertyChanging();
					this._Pret = value;
					this.SendPropertyChanged("Pret");
					this.OnPretChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Avioane_Bilete", Storage="_Avioane", ThisKey="ID_Avion", OtherKey="ID_Avion", IsForeignKey=true)]
		public Avioane Avioane
		{
			get
			{
				return this._Avioane.Entity;
			}
			set
			{
				Avioane previousValue = this._Avioane.Entity;
				if (((previousValue != value) 
							|| (this._Avioane.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Avioane.Entity = null;
						previousValue.Biletes.Remove(this);
					}
					this._Avioane.Entity = value;
					if ((value != null))
					{
						value.Biletes.Add(this);
						this._ID_Avion = value.ID_Avion;
					}
					else
					{
						this._ID_Avion = default(int);
					}
					this.SendPropertyChanged("Avioane");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Calatori_Bilete", Storage="_Calatori", ThisKey="ID_Calator", OtherKey="ID_Calator", IsForeignKey=true)]
		public Calatori Calatori
		{
			get
			{
				return this._Calatori.Entity;
			}
			set
			{
				Calatori previousValue = this._Calatori.Entity;
				if (((previousValue != value) 
							|| (this._Calatori.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Calatori.Entity = null;
						previousValue.Biletes.Remove(this);
					}
					this._Calatori.Entity = value;
					if ((value != null))
					{
						value.Biletes.Add(this);
						this._ID_Calator = value.ID_Calator;
					}
					else
					{
						this._ID_Calator = default(Nullable<int>);
					}
					this.SendPropertyChanged("Calatori");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
